### PR TITLE
AS-139: Add import status endpoints

### PR DESCRIPTION
**Pull request by MatthewBemis**

### CODE REVIEW

**Review by helgridly — CHANGES_REQUESTED** [review]
buncha nits and style things but this is good!

**Review by davidangb — COMMENTED** [review]
some comments inline

**Review by davidangb — COMMENTED** [review]
two more comments ...

**Review by davidangb — APPROVED** [review]
:+1: lgtm, and I defer to @helgridly for python best practices

**Review by helgridly — APPROVED** [review]
i have a couple final comments but i'll thumb pending them

**Pull request merged**
