### PR TITLE
Re-arrange repo structure to include cleanup_scripts in Jenkins jobs

### PR DESCRIPTION
**Pull request by aaronkanzer**
Resolves error in https://fc-jenkins.dsp-techops.broadinstitute.org/blue/organizations/jenkins/general-deploy/detail/general-deploy/1221/pipeline

### CODE REVIEW

**Review by sagehen03 — APPROVED** [review]

**Review by davidangb — COMMENTED** [review]
moving the `cleanup_scripts` directory into the `app` directory means that the scripts will get packaged up and deployed to App Engine, and the scripts will become part of the running app. I suppose that isn't a showstopper, but it's not ideal.

Some thoughts:
* is there anything in app.yaml or elsewhere during the deploy to GAE that we could use to exclude `cleanup_scripts` from being deployed?
* could you modify the `docker run` invocation to mount the `cleanup_scripts` into some other directory and run them from there, without holding them under `/app`?

**Comment by davidangb** [comment]
ahh - take a look at the `.gcloudignore` file, I think that might help!

**Review by davidangb — APPROVED** [review]
once this successfully deploys to dev, would you double-check that the .gcloudignore is working as expected? I think you can do that by browsing the deployed source within Google Cloud Console.

**Comment by aaronkanzer** [comment]
@davidangb will do!

**Pull request merged**
